import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://qhisportalppr.moph.gov.qa/payer/#/ic/signin');
  await page.getByText('Sign up', { exact: true }).click();
  await page.locator('#mat-input-0').click();
  await page.locator('#mat-input-0').fill('638378');
  await page.locator('ng-select').filter({ hasText: '×CR No' }).getByRole('combobox').click();
  await page.getByText('Establishment No', { exact: true }).click();
  await page.locator('mat-card').filter({ hasText: '1. Insurance Company (IC)' }).locator('input[type="text"]').nth(1).click();
  await page.locator('mat-card').filter({ hasText: '1. Insurance Company (IC)' }).locator('input[type="text"]').nth(1).fill('638378');
  await page.locator('mat-card').filter({ hasText: '1. Insurance Company (IC)' }).locator('input[type="text"]').nth(1).press('Tab');
  await page.locator('#mat-input-1').fill('Test Insurance Company Auto');
  await page.locator('#mat-input-1').press('Tab');
  await page.locator('#mat-input-2').click();
  await page.locator('#mat-input-2').fill('Test Insurance company Auto');
  await page.locator('#mat-input-2').press('Tab');
  await page.locator('#mat-input-3').click();
  await page.locator('#mat-input-3').fill('Jack pandi');
  await page.locator('#mat-input-3').press('Tab');
  await page.locator('#mat-input-6').click();
  await page.getByRole('button', { name: '07/07/' }).click();
  await page.locator('#mat-input-7').click();
  await page.getByRole('button', { name: 'Next month' }).click();
  await page.getByRole('button', { name: 'Next month' }).click();
  await page.getByRole('button', { name: 'Next month' }).click();
  await page.getByRole('button', { name: '09/10/' }).click();
  await page.locator('#mat-input-16').click();
  await page.locator('#mat-input-16').fill('63738797');
  await page.locator('#mat-input-16').press('Tab');
  await page.locator('#mat-input-8').click();
  await page.locator('#mat-input-8').fill('testinsurance@yopmail.com');
  await page.locator('#mat-input-8').press('Tab');
  await page.locator('mat-card').filter({ hasText: '1. Insurance Company (IC)' }).locator('input[type="text"]').nth(2).click();
  await page.getByRole('option', { name: 'QCB' }).click();
  await page.locator('#mat-input-9').click();
  await page.locator('#mat-input-9').fill('office header');
  await page.locator('#mat-input-10').click();
  await page.locator('#mat-input-10').fill('63738');
  await page.locator('#mat-input-10').press('Tab');
  await page.locator('#mat-input-11').fill('73830');
  await page.locator('#mat-input-11').press('Tab');
  await page.locator('#mat-input-12').fill('37378');
  await page.locator('#mat-input-12').press('Tab');
  await page.locator('div').filter({ hasText: /^Zone\*$/ }).getByRole('textbox').click();
  await page.getByRole('option', { name: '67' }).click();
  await page.locator('#mat-input-17').click();
  await page.locator('#mat-input-17').fill('municaptu');
  await page.locator('#mat-input-17').press('Tab');
  await page.locator('#mat-input-13').fill('63738797');
  await page.locator('#mat-input-13').press('Tab');
  await page.locator('#mat-input-14').fill('www.testinsurance.com');
  await page.locator('#mat-input-14').press('Tab');
  await page.locator('#mat-input-18').click();
  await page.locator('#mat-input-18').click();
  await page.locator('#mat-input-18').fill('29435619571');
  await page.locator('#mat-input-18').press('Tab');
  await page.locator('#mat-input-20').click();
  await page.locator('#mat-input-20').fill('safvan@yopmail.com');
  await page.locator('#mat-input-20').press('Tab');
  await page.locator('#mat-input-21').fill('operations');
  await page.locator('#mat-input-21').press('Tab');
  await page.getByText('+').nth(1).click();
  await page.locator('#mat-input-22').fill('73783793');
  await page.getByText('Drag and Drop Select a file or drop one hereadd').first().click();
  await page.locator('body').setInputFiles('Warning Notification - Delay Execution - 7 days.pdf');
  await page.getByText('Drag and Drop Select a file').nth(1).click();
  await page.locator('body').setInputFiles('Warning Notification - Delay Resolution - 7 days.pdf');
  await page.pause()
  await page.locator('label span').click();
  await page.getByLabel('', { exact: true }).press('Tab');
  await page.getByRole('button', { name: 'Back' }).press('Enter');
});